server:
  port: 8089
app:
  roles:
    admin: ADMIN
    teacher: TEACHER
    student: STUDENT
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5439/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: method